import gzip
import json
from pathlib import Path
from pprint import pformat


DIFFICULTIES = ["easy", "medium", "hard", "expert"]
REPLAY_DIR = Path("replays")
OUTPUT_PATH = Path("hardcoded_maps.py")


def load_first_replay(path: Path) -> dict:
    with gzip.open(path, "rt") as f:
        payload = json.load(f)

    if isinstance(payload, dict) and "trajectory" in payload:
        return payload
    if isinstance(payload, dict) and isinstance(payload.get("replays"), list):
        if not payload["replays"]:
            raise ValueError(f"No replays in {path}")
        return payload["replays"][0]
    if isinstance(payload, list):
        if not payload:
            raise ValueError(f"No replays in {path}")
        return payload[0]

    raise ValueError(f"Unsupported replay format in {path}")


def extract_map_from_replay(replay: dict) -> dict:
    if "trajectory" not in replay or not replay["trajectory"]:
        raise ValueError("Replay has no trajectory")

    state = replay["trajectory"][0]["state"]
    grid = state["grid"]

    return {
        "grid": {
            "width": grid["width"],
            "height": grid["height"],
            "walls": grid["walls"],
        },
        "bots": [
            {
                "id": bot["id"],
                "position": bot["position"],
                "inventory": bot.get("inventory", []),
            }
            for bot in state["bots"]
        ],
        "items": [
            {
                "id": item["id"],
                "type": item["type"],
                "position": item["position"],
            }
            for item in state["items"]
        ],
        "drop_off": state["drop_off"],
    }


def main() -> None:
    maps = {}
    for difficulty in DIFFICULTIES:
        replay_path = REPLAY_DIR / f"{difficulty}.json.gz"
        replay = load_first_replay(replay_path)
        maps[difficulty] = extract_map_from_replay(replay)

    content = (
        "# Auto-generated by get_maps.py\n"
        "# Hardcoded maps extracted from first replay per difficulty.\n\n"
        f"HARDCODED_MAPS = {pformat(maps, width=100, sort_dicts=False)}\n\n"
        "for _map in HARDCODED_MAPS.values():\n"
        "    _map['_wall_set'] = set(map(tuple, _map['grid']['walls']))\n"
        "del _map\n"
    )
    OUTPUT_PATH.write_text(content)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
